version: '3'

services:

  web.customized-calendar:
    container_name: web.customized-calendar.dev
    image: nginx:1.23.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./application:/app
    networks:
      - customized-calendar-network
    depends_on:
      - api.customized-calendar

  api.customized-calendar:
    container_name: api.customized-calendar.dev
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./application:/app
    networks:
      - customized-calendar-network
    depends_on:
      - maria-db

  maria-db:
    container_name: db.customized-calendar.dev
    image: 'mariadb:10.11.3'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    env_file:
      - ./application/.env
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'customized_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'customized-calendar-mariadb_data:/var/lib/mysql'
    networks:
      - customized-calendar-network

networks:
  customized-calendar-network:
    driver: bridge

volumes:
  customized-calendar-mariadb_data:
    driver: local
